server:
  port: 8083

cliente:
  service:
    url: http://localhost:8082

spring:
  r2dbc:
    url: r2dbc:h2:mem:///polizasdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

resilience4j:
  circuitbreaker:
    instances:
      clienteService:
        slidingWindowSize: 5
        failureRateThreshold: 50