server:
  port: 8083

cliente:
  service:
    url: http://localhost:8082

spring:
  datasource:
    url: jdbc:h2:mem:polizasdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

resilience4j:
  circuitbreaker:
    instances:
      clienteService:
        slidingWindowSize: 5
        failureRateThreshold: 50
